# Alias of memory/hei_nw
# Episodic memory preset using HEI-NW store with replay and gating.
gating_enabled: true
dataset_profile: hard
memory:
  episodic:
    gate:
      enabled: ${gating_enabled}
    use_completion: true
replay:
  cycles: 1
  samples: 3
retrieval:
  enabled: true

# Generation/encoding tweaks (consumed by scripts/eval_model.py)
use_chat_template: true
system_prompt: "Answer with the exact shortest span from the prompt. No explanations."
max_new_tokens: 8
