# Spatial/procedural memory preset using SMPD store with replay and gating.
gating_enabled: true
memory:
  spatial:
    gate:
      enabled: true
replay:
  cycles: 1
retrieval:
  enabled: true

# Generation/encoding tweaks (consumed by scripts/eval_model.py)
use_chat_template: true
system_prompt: "Answer with the exact shortest span from the prompt. No explanations."
max_new_tokens: 8
