# Relational memory configuration.
# Optional: seed schemas for fast-track routing (use with simple fixtures)
# schemas:
#   - { name: "rel", relation: "rel" }

# Summary: settings for SGC-RSS knowledge graph. Defaults mirror EVAL_PLAN ยง3.2.

# Minimum confidence for ``SchemaIndex`` fast-track routing; default 0.7.
schema_threshold: 0.7

# Enable lightweight message-passing updates to node embeddings; default true.
gnn_updates: true

# Pruning parameters for low-confidence or old tuples.
prune:
  min_conf: 0.2   # drop tuples below this confidence
  max_age: 86400  # seconds (1 day)

# Gate controlling tuple writes; toggle via ``memory.relational.gate.enabled``
gate:
  enabled: true
  threshold: 0.6
  w_conf: 0.6
  w_nov: 0.5
  w_deg: 0.4
  w_rec: 0.2
  max_degree: 64

