# Spatial memory configuration.

# Summary: settings for SMPD place graph. Defaults mirror EVAL_PLAN ยง3.3.

# Gating weight controlling transition updates; default 1.0.
gating_weights:
  transition: 1.0

# Remove places and edges that haven't been observed for a number of steps.
prune:
  max_age: 1000  # steps; see EVAL_PLAN ยง3.3

# Gate regulating map growth; toggle via ``memory.spatial.gate.enabled``
gate:
  enabled: true
  block_threshold: 1.0
  repeat_N: 3
  recent_window: 20
  max_degree: 64

