# Training configuration.

# Run metadata for reproducibility.
seed: 0
run_name: default
notes: ""

# Relative weighting for episodic replay during training.
replay_weight: 0.5

# Global gating weights.
gating_weights:
  write: 1.0
  recall: 0.5

# Efficiency toggles.
efficiency:
  flash_attention: false

