# Default training configuration.

# Run metadata for reproducibility.
seed: 0
run_name: default
notes: ""

data_format: "jsonl"
train_files: []
val_files: []

fusion_insert_block_index: -4
use_episodic: false
use_relational: false
use_spatial: false

replay:
  enabled: false
  ratio: 0.30

learning_rate: 0.001

# Efficiency toggles.
efficiency:
  flash_attention: false
