episodic:
  distractors: 0
episodic_multi:
  distractors: 8
  corrections: true
episodic_cross:
  entity_pool: 4
episodic_capacity:
  context_budget: 256
semantic:
  hop_depth: 2
  inject_contradictions: false
spatial:
  grid_size: 5
  obstacle_density: 0.2
