episodic_cross:
  entity_pool: 8
semantic:
  hop_depth: 2
  inject_contradictions: true
  distractors: 0
  entity_pool: 4
  paraphrase_prob: 0.0
  ambiguity_prob: 0.0
spatial_multi:
  grid_size: 6
  obstacle_density: 0.25
