episodic:
  distractors: 2
episodic_multi:
  distractors: 10
  corrections: true
episodic_cross:
  entity_pool: 6
episodic_capacity:
  context_budget: 384
semantic:
  hop_depth: 2
  inject_contradictions: true
spatial:
  grid_size: 6
  obstacle_density: 0.25
