episodic:
  distractors: 0
episodic_multi:
  distractors: 8
  corrections: true
episodic_cross:
  entity_pool: 4
episodic_capacity:
  context_budget: 256
semantic:
  hop_depth: 2
  inject_contradictions: false
  distractors: 0
  entity_pool: 4
  paraphrase_prob: 0.0
  ambiguity_prob: 0.0
spatial:
  grid_size: 5
  obstacle_density: 0.2
