name: Nightly
on:
  schedule:
    - cron: "0 2 * * *" # 02:00 UTC daily
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install
        run: pip install -e . -r codex-env/requirements.txt
      - name: Integration (CLI/Hydra) + Slow
        run: |
          pytest -q --runintegration --runslow
